# Generated by Django 2.2 on 2019-04-29 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190429_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 4, 29, 21, 40, 45, 483005)),
        ),
    ]
